apiVersion: v1
kind: Pod # case-sensitive
metadata:
  name: nginx
  labels: # dictionary, as many entries as you want
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
